### ISSUE TITLE
Remove bootstrap requirement

### ISSUE THREAD

**Issue by Sammaye** [lordthorzonus/yii2-algolia#17]
Having to bootstrap this entire ext for one controller in a console application is a bit OTT.

I can understand bootstrapping `log` or `debug` but I cannot see why I must bootstrap this ext to correctly use it.

The main problem is that the code which interacts with the ext is relying on `$container` having the manager component set and this sounds a bit wrong logically speaking.

It would be better to re-code it so that it properly uses the manager property in the base algolia component.

**Comment by lordthorzonus** [comment]
Hi! The bootstrapping is required for registering the `AlgoliaManager` into the DI container as the recommended way of using this package is through dependency injection. The bootstrap only registers it into the container: https://github.com/lordthorzonus/yii2-algolia/blob/master/src/AlgoliaComponent.php#L122 which causes very little overhead as the callable  is invoked only when the dependency is actually resolved.  This is the recommended way of doing it in Yii2 http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#when-to-register-dependencies . 

You can however leave the bootstrapping out and then just access the component through the Yii god object `Yii::$app->algolia->...`. Then just the dependency injection won't work and the code is probably more difficult to test :). 

Does this solve your problem?

**Comment by Sammaye** [comment]
Unfortunately it does not, here https://github.com/lordthorzonus/yii2-algolia/blob/master/src/ActiveRecord/SynchronousAutoIndexBehavior.php#L43 it relies on the bootstrap code having run

**Comment by Sammaye** [comment]
Of course that is just one example

**Comment by lordthorzonus** [comment]
Ah yeah sorry forgot about that. The other solution there would be to hard code the component name which is really bad in my opinion. 

But if you are attaching the behavior or using the active record helpers you are probably utilizing the package in more places than just one controller?  

Relying on the dependency injection is just a way to make the code decoupled and the defacto way of building good packages in modern frameworks. Look for example how the laravel package works : https://github.com/algolia/algoliasearch-laravel/blob/master/src/AlgoliaServiceProvider.php (ServiceProvider there is equal to bootstrapping a component in Yii). 

I can guarantee that bootstrapping this will cause no overhead :). We are also using this in production. 

If you have a better way to suggest where to register the dependencies to the container I'm happy to accept a PR for this!

**Comment by Sammaye** [comment]
For the console application, which is part of an advanced Yii2 application structure I use it in one model and one controller

**Comment by Sammaye** [comment]
For example: searching is done strictly via JS and only indexing is done in PHP

**Comment by Sammaye** [comment]
I think the main problem is probably not using the DI container but using it on a unpredictable element, the manager. If you was to DI the component as soon as someone calls it on their end then you can have dynamic accession while allowing someone to just quickly construct the God object for a single task

**Comment by Sammaye** [comment]
Hmm, no that wouldn't work since the accession could be without ever calling the ext on their side

**Comment by Sammaye** [comment]
Ah I think I'll drop this for the min, there is no way to make both of our agendas work, I'll just bootstrap it

**Comment by lordthorzonus** [comment]
If you just want to do indexing all the methods in the AlgoliaManager are available without bootstrapping accessing through the `Yii::$app->algolia`.  Just the instance mehtods on ActiveRecord helper trait and the behavior relies on resolving the AlgoliaManager through the container. 

I think i'll add a note of this to the README. Thank you :).

**Comment by Sammaye** [comment]
I want both really, so I want to create an admin controller for full index but also allow people using the UI to save with the active record, so the console app would just load it for one single action in a controller but the backend app would load it for the active record and the frontend would not load it at all
