### ISSUE TITLE
A dismissable error should arise when attempting to save a document exceeding the size limit

### ISSUE THREAD

**Issue by Sammaye** [lordthorzonus/yii2-algolia#18]
My project involves large ecommerce documents, sometimes they may accidentally grow over the 10KB default limit algolia have.

It would be good if a warning or non-blocking error was risen to tell the user within the active record hooks, `afterInsert` and `afterUpdate` or maybe within the actual manager's functions.

**Comment by lordthorzonus** [comment]
Hi the Algolia php client already throws meaningful exceptions for this case. For example: `AlgoliaSearch\AlgoliaException: Record at the position 0 is too big size=135473 bytes. Contact us if you need an extended quota` So when indexing you can wrap the methods around a try catch block and handle the exceptions.

For the behavior it's now bit harder to catch the exceptions.. Do you think it would be a good solution if the afterUpdate, afterInsert etc. would be their own protected methods? Then you could quite easily extend the behavior and do the logging etc. there?

The best way to prevent this from happening at all is to explicitly define what attributes of the ActiveRecord is indexed in the getAlgoliaRecord method.

**Comment by Sammaye** [comment]
Weird, I need to investigate why it isn't throwing them for me then when I index anything as large as 16kb.

Hmm, as for implementation I was personally thinking of just hard coding a `Yii::warning` personally since I have found, from my own algolia panel, that the document is still indexed it just is not searchable so it doesn't seem to be a stopping error (when I first started out I accidentally indexed a 66KB document that went into my control panel successfully) but one a warning notice that something bad has happened.

> The best way to prevent this from happening at all is to explicitly define what attributes of the ActiveRecord is indexed in the getAlgoliaRecord method

Oh I do I have overridden the method but even indexing what I need I can sometimes accidentally go over, it is only like once in 200,000 records but it was once.

**Comment by lordthorzonus** [comment]
Hmm that's strange according to their FAQ they should always throw that error : https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records

Basically in code it's done here: https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L742

There's some discussion here : https://github.com/algolia/algoliasearch-client-php/pull/135 that they allow some margin but I would believe indexing 66kb wouldn't be possible without some bug on Algolia side. 

For the hardcoding I don't want to dictate how the exceptions are handled in other peoples code as there can be numerous use cases. We for example are sending email warnings to admins if something happens on the nightly Algolia sync.  

But as it's not now so easily done if using the behavior I should definitely improve that! :).

**Comment by Sammaye** [comment]
This calls for some investigation of my lib in the morning :)

**Comment by Sammaye** [comment]
Fascinating, after a bit more investigation I believe my account is unique. I have talked to the algolia team a few times and I think they may have made some special provisions for my account which allows me to index anything I want (!).

It is a bit strange since it still errors out in the UI when there is a document greater than 10KB, so probably need to implement something to throw an error since I only get one if a specific element in a document is over 16KB now.

I notice one person in that thread had a 100KB upgrade for their account, it is likely we have this too, despite algolia never telling us and keeping it quiet (they tell us to AJAX load our additional search results :/).

But coming back to this specific issue: normally the extension wouldn't need to deal with this, it is more that my account is in some strange position where I have an upgrade that I was never told about. With this in mind it is probably better for me to make special provisions for my situation rather than change the extension for everyone.

What do you think?

**Comment by lordthorzonus** [comment]
I'll add a todo for myself for next week to check how to more easily extend the behaviour :). That should allow you to depend on the functionality by this package and make your custom rules more easily. I think the basic manager is already quite easily handleable. 

Can I mark this issue as closed?

**Comment by Sammaye** [comment]
Sure :) thanks!
