### ISSUE TITLE
Add a little something about needing to overwrite the getObjectID() function if your ObjectID is not the getPrimaryKey()

### ISSUE THREAD

**Issue by Sammaye** [lordthorzonus/yii2-algolia#19]
Just a short note or something

**Comment by lordthorzonus** [comment]
Hi this has been added to documentation! Sorry for taking long :).

**Comment by lordthorzonus** [comment]
And released along small changes in https://github.com/lordthorzonus/yii2-algolia/releases/tag/1.1.1
