### ISSUE TITLE
Add entry to awesome-algolia repository

### ISSUE THREAD

**Issue by rayrutjes** [lordthorzonus/yii2-algolia#23]
Your repository looks amazing 😍 

We would gladly list it on the [awesome-algolia](/algolia/awesome-algolia) repository.

Feel free to submit a PR there. ❤️

**Comment by lordthorzonus** [comment]
Thanks for the compliment 💟 and an awesome product! Opened a PR :) https://github.com/algolia/awesome-algolia/pull/17
